[package]
name = "application"
version = "1.0.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
actix-rt = "2.7.0"
async-trait = "0.1.57"
bson = { version = "2.1.0", features = ["chrono-0_4"] }
regex = "1.7.1"

[dev-dependencies]
mockall = "0.11.3"
