[package]
name = "domain"
version = "1.0.0"
edition = "2021"


[dependencies]
bson = { version = "2.1.0", features = ["chrono-0_4"] }
chrono = "0.4"
derive_more = "0.99"
serde = { version = "1.0", features = ["derive"] }
